project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    tools:
      - icon: linkedin
        href: "https://personal.yout.ing"
      - icon: github
        href: "https://github.com/ytquek"
    left:
      - text: In class Exercise
        menu: 
          - text: "In Class Exercise 1"
            href: "In_class_ex/In-class_Ex01.html"
          - text: "In Class Exercise 2"
            href: "In_class_ex/In-class_Ex02.html"
          - text: "In Class Exercise 4"
            href: "In_class_ex/In-class_Ex4.html"
          - text: "In Class Exercise 5"
            href: "In_class_ex/In-class_ex5.html"
      - text: Hands on Exercise
        menu:
          - text: "Hands On Exercise 1"
            href: "In_class_ex/hands_on_ex1.html"
          - text: "Hands On Exercise 2"
            href: "In_class_ex/hands_on_ex1.html"
          - text: "Hands On Exercise 3"
            href: "In_class_ex/hands-on_ex3.html"
          - text: "Hands On Exercise 3 Part 2"
            href: "In_class_ex/hands-on_ex3_2.html"
          - text: "Hands On Exercise 4 Part 1"
            href: "In_class_ex/hands-on_ex4.html"
          - text: "Hands On Exercise 4 Part 2"
            href: "In_class_ex/hands-on_ex4_2.html"
          - text: "Hands On Exercise 4 Part 3"
            href: "In_class_ex/hands-on_ex4_3.html"
          - text: "Hands On Exercise 5"
            href: "In_class_ex/Hands-on_Ex5.html"
          - text: "Hands On Exercise 6"
            href: "In_class_ex/Hands-on_Ex6.html"
      - text: Take Home Exercise
        menu:
          - text: "Take Home Exercise 1"
            href: "take_home_ex/take_home_ex1.html"
          - text: "Take Home Exercise 2"
            href: "take_home_ex/take_home_ex2.html"
    sidebar:
    contents: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

