project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    tools:
      - icon: linkedin
        href: personal.yout.ing
      - icon: github
        href: https:github.com/ytquek
    left:
      - text: In class Exercise
        menu: 
          - text: "In Class Exercise 1"
            href: "In_class_ex/In-class_Ex01.html"
          - text: "In Class Exercise 2"
            href: "In_class_ex/In-class_Ex02.html"
      - text: Hands on Exercise
        menu:
          - text: "Hands On Exercise 1"
            href: "In_class_ex/hands_on_ex1.html"
          - text: "Hands On Exercise 2"
            href: "In_class_ex/hands_on_ex1.html"
          - text: "Hands On Exercise 3"
            href: "In_class_ex/hands-on_ex3.html"
      - text: Take Home Exercise
        menu:
          - text: "Take Home Exercise 1"
            href: "take_home_ex/take_home_ex1.html"
    sidebar:
    contents: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

